package es.sebas1705.ui.theme

import androidx.compose.ui.graphics.Color

// Light low contrast color palette
val primaryLightLowContrast = Color(0xFFB31246)
val onPrimaryLightLowContrast = Color(0xFFFFFFFF)
val primaryContainerLightLowContrast = Color(0xFFFFD9E4)
val onPrimaryContainerLightLowContrast = Color(0xFF3F0014)
val secondaryLightLowContrast = Color(0xFF007C8A)
val onSecondaryLightLowContrast = Color(0xFFFFFFFF)
val secondaryContainerLightLowContrast = Color(0xFFB7F1F7)
val onSecondaryContainerLightLowContrast = Color(0xFF002125)
val tertiaryLightLowContrast = Color(0xFF336A8E)
val onTertiaryLightLowContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightLowContrast = Color(0xFFCCE5F8)
val onTertiaryContainerLightLowContrast = Color(0xFF001E30)
val errorLightLowContrast = Color(0xFF904A43)
val onErrorLightLowContrast = Color(0xFFFFFFFF)
val errorContainerLightLowContrast = Color(0xFFFFDAD6)
val onErrorContainerLightLowContrast = Color(0xFF3B0907)
val backgroundLightLowContrast = Color(0xFFF7FAFF)
val onBackgroundLightLowContrast = Color(0xFF121C22)
val surfaceLightLowContrast = Color(0xFFF2F8FC)
val onSurfaceLightLowContrast = Color(0xFF121C22)
val surfaceVariantLightLowContrast = Color(0xFFD7E3EB)
val onSurfaceVariantLightLowContrast = Color(0xFF3A4A54)
val outlineLightLowContrast = Color(0xFF6B7C87)
val outlineVariantLightLowContrast = Color(0xFFB8C7D0)
val scrimLightLowContrast = Color(0xFF000000)
val inverseSurfaceLightLowContrast = Color(0xFF27343C)
val inverseOnSurfaceLightLowContrast = Color(0xFFEAF2F7)
val inversePrimaryLightLowContrast = Color(0xFFFFB1C8)
val surfaceDimLightLowContrast = Color(0xFFD0DDE6)
val surfaceBrightLightLowContrast = Color(0xFFF2F8FC)
val surfaceContainerLowestLightLowContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightLowContrast = Color(0xFFEBF2F8)
val surfaceContainerLightLowContrast = Color(0xFFE5EDF4)
val surfaceContainerHighLightLowContrast = Color(0xFFE0E8F0)
val surfaceContainerHighestLightLowContrast = Color(0xFFDCE4EB)
//--------------------------------------------------------------------

// Light medium contrast color palette
val primaryLightMediumContrast = Color(0xFF8A0045)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFC9467F)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF006B8E)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF3B99C3)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF22317C)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF4A5AB5)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF6E302A)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFAA6057)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF7FF)
val onBackgroundLightMediumContrast = Color(0xFF1D1A20)
val surfaceLightMediumContrast = Color(0xFFF5FAFB)
val onSurfaceLightMediumContrast = Color(0xFF161D1D)
val surfaceVariantLightMediumContrast = Color(0xFFDFE4D7)
val onSurfaceVariantLightMediumContrast = Color(0xFF3F453B)
val outlineLightMediumContrast = Color(0xFF5B6156)
val outlineVariantLightMediumContrast = Color(0xFF777D71)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3232)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F2)
val inversePrimaryLightMediumContrast = Color(0xFFFFA8CD)
val surfaceDimLightMediumContrast = Color(0xFFD5DBDC)
val surfaceBrightLightMediumContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F5)
val surfaceContainerLightMediumContrast = Color(0xFFE9EFEF)
val surfaceContainerHighLightMediumContrast = Color(0xFFE3E9EA)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDEE4E4)
//--------------------------------------------------------------------

// Light high contrast color palette
val primaryLightHighContrast = Color(0xFF5A002D)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF8A0045)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF004A65)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF006B8E)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF10226B)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF22317C)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF44100C)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF6E302A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF7FF)
val onBackgroundLightHighContrast = Color(0xFF1D1A20)
val surfaceLightHighContrast = Color(0xFFF5FAFB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDFE4D7)
val onSurfaceVariantLightHighContrast = Color(0xFF20251D)
val outlineLightHighContrast = Color(0xFF3F453B)
val outlineVariantLightHighContrast = Color(0xFF3F453B)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3232)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFD9E7)
val surfaceDimLightHighContrast = Color(0xFFD5DBDC)
val surfaceBrightLightHighContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEFF5F5)
val surfaceContainerLightHighContrast = Color(0xFFE9EFEF)
val surfaceContainerHighLightHighContrast = Color(0xFFE3E9EA)
val surfaceContainerHighestLightHighContrast = Color(0xFFDEE4E4)
//--------------------------------------------------------------------

// Dark low contrast color palette
val primaryDarkLowContrast = Color(0xFFFFB1C8)
val onPrimaryDarkLowContrast = Color(0xFF640028)
val primaryContainerDarkLowContrast = Color(0xFF8B0B3A)
val onPrimaryContainerDarkLowContrast = Color(0xFFFFD9E4)
val secondaryDarkLowContrast = Color(0xFF7EDCE7)
val onSecondaryDarkLowContrast = Color(0xFF00363D)
val secondaryContainerDarkLowContrast = Color(0xFF00525C)
val onSecondaryContainerDarkLowContrast = Color(0xFFB7F1F7)
val tertiaryDarkLowContrast = Color(0xFF9FCBE6)
val onTertiaryDarkLowContrast = Color(0xFF00344F)
val tertiaryContainerDarkLowContrast = Color(0xFF1B4D6C)
val onTertiaryContainerDarkLowContrast = Color(0xFFCCE5F8)
val errorDarkLowContrast = Color(0xFFFFB4AB)
val onErrorDarkLowContrast = Color(0xFF561E19)
val errorContainerDarkLowContrast = Color(0xFF73332D)
val onErrorContainerDarkLowContrast = Color(0xFFFFDAD6)
val backgroundDarkLowContrast = Color(0xFF07131B)
val onBackgroundDarkLowContrast = Color(0xFFDCE7EE)
val surfaceDarkLowContrast = Color(0xFF0B171F)
val onSurfaceDarkLowContrast = Color(0xFFDCE7EE)
val surfaceVariantDarkLowContrast = Color(0xFF3F4B54)
val onSurfaceVariantDarkLowContrast = Color(0xFFBECAD3)
val outlineDarkLowContrast = Color(0xFF8897A1)
val outlineVariantDarkLowContrast = Color(0xFF3F4B54)
val scrimDarkLowContrast = Color(0xFF000000)
val inverseSurfaceDarkLowContrast = Color(0xFFDCE7EE)
val inverseOnSurfaceDarkLowContrast = Color(0xFF243038)
val inversePrimaryDarkLowContrast = Color(0xFFB31246)
val surfaceDimDarkLowContrast = Color(0xFF0B171F)
val surfaceBrightDarkLowContrast = Color(0xFF2D3A43)
val surfaceContainerLowestDarkLowContrast = Color(0xFF040E14)
val surfaceContainerLowDarkLowContrast = Color(0xFF0F1B23)
val surfaceContainerDarkLowContrast = Color(0xFF142028)
val surfaceContainerHighDarkLowContrast = Color(0xFF1E2A33)
val surfaceContainerHighestDarkLowContrast = Color(0xFF28343D)
//--------------------------------------------------------------------

// Dark medium contrast color palette
val primaryDarkMediumContrast = Color(0xFFFFB7D6)
val onPrimaryDarkMediumContrast = Color(0xFF420020)
val primaryContainerDarkMediumContrast = Color(0xFFC9467F)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF9EE0FF)
val onSecondaryDarkMediumContrast = Color(0xFF002535)
val secondaryContainerDarkMediumContrast = Color(0xFF3B99C3)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC6CEFF)
val onTertiaryDarkMediumContrast = Color(0xFF000A46)
val tertiaryContainerDarkMediumContrast = Color(0xFF4A5AB5)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF330404)
val errorContainerDarkMediumContrast = Color(0xFFCC7B72)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF151218)
val onBackgroundDarkMediumContrast = Color(0xFFE7E0E8)
val surfaceDarkMediumContrast = Color(0xFF0E1415)
val onSurfaceDarkMediumContrast = Color(0xFFF6FCFC)
val surfaceVariantDarkMediumContrast = Color(0xFF43483F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC7CDC0)
val outlineDarkMediumContrast = Color(0xFF9FA599)
val outlineVariantDarkMediumContrast = Color(0xFF7F857A)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE4E4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2C)
val inversePrimaryDarkMediumContrast = Color(0xFF8A0045)
val surfaceDimDarkMediumContrast = Color(0xFF0E1415)
val surfaceBrightDarkMediumContrast = Color(0xFF343A3B)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF090F10)
val surfaceContainerLowDarkMediumContrast = Color(0xFF161D1D)
val surfaceContainerDarkMediumContrast = Color(0xFF1A2121)
val surfaceContainerHighDarkMediumContrast = Color(0xFF252B2C)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF303637)
//--------------------------------------------------------------------

// Dark high contrast color palette
val primaryDarkHighContrast = Color(0xFFFFEDF3)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFB7D6)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFEAF8FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF9EE0FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF1F2FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC6CEFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF151218)
val onBackgroundDarkHighContrast = Color(0xFFE7E0E8)
val surfaceDarkHighContrast = Color(0xFF0E1415)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF43483F)
val onSurfaceVariantDarkHighContrast = Color(0xFFF7FDEF)
val outlineDarkHighContrast = Color(0xFFC7CDC0)
val outlineVariantDarkHighContrast = Color(0xFFC7CDC0)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE4E4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF5A002D)
val surfaceDimDarkHighContrast = Color(0xFF0E1415)
val surfaceBrightDarkHighContrast = Color(0xFF343A3B)
val surfaceContainerLowestDarkHighContrast = Color(0xFF090F10)
val surfaceContainerLowDarkHighContrast = Color(0xFF161D1D)
val surfaceContainerDarkHighContrast = Color(0xFF1A2121)
val surfaceContainerHighDarkHighContrast = Color(0xFF252B2C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF303637)
//--------------------------------------------------------------------





